Pass archive_host to get_book_nodes and generate_cnx_uris
When running the example usage:

```
Traceback (most recent call last):
  File "./py3/bin/rex_redirects", line 11, in <module>
    load_entry_point('cnx-rex-redirects', 'console_scripts', 'rex_redirects')()
  File "/home/karen/src/cnx-rex-redirects/py3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/karen/src/cnx-rex-redirects/py3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/karen/src/cnx-rex-redirects/py3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/karen/src/cnx-rex-redirects/py3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/karen/src/cnx-rex-redirects/py3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/karen/src/cnx-rex-redirects/py3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/karen/src/cnx-rex-redirects/rex_redirects.py", line 190, in generate_cnx_uris_for_rex_books
    for uri in generate_cnx_uris(book):
  File "/home/karen/src/cnx-rex-redirects/rex_redirects.py", line 151, in generate_cnx_uris
    nodes = list(get_book_nodes(book_id))
TypeError: get_book_nodes() missing 1 required positional argument: 'book_id'
```